//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emialid { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string password { get; set; }
        public string skillset { get; set; }
        public Nullable<int> overallexperience { get; set; }
        public string skillindividual { get; set; }
        public string biodatapath { get; set; }
        public string noticeperiod { get; set; }
    }
}
