//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long clientId { get; set; }
        public string clientname { get; set; }
        public string phone { get; set; }
        public string country { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
