//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalary
    {
        public long salaryId { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<decimal> basicSalary { get; set; }
        public Nullable<decimal> da { get; set; }
        public Nullable<decimal> ta { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public string financialYear { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> paidLeaves { get; set; }
        public Nullable<decimal> mustTakeLeave { get; set; }
        public Nullable<decimal> consumedLeaves { get; set; }
        public Nullable<decimal> balance { get; set; }
    }
}
