//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int id { get; set; }
        public Nullable<System.DateTime> interviewdate { get; set; }
        public Nullable<int> jobid { get; set; }
        public Nullable<int> employeeid { get; set; }
        public Nullable<int> interviewid { get; set; }
        public string interviewtype { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<long> branchId { get; set; }
    }
}
