//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobPost
    {
        public long jobId { get; set; }
        public string jobTilte { get; set; }
        public string skills { get; set; }
        public Nullable<int> noOfVacancies { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<long> approvedBy { get; set; }
        public string remarks { get; set; }
        public Nullable<int> branchid { get; set; }
    }
}
