//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsAppliedFor
    {
        public int id { get; set; }
        public Nullable<int> jobpostid { get; set; }
        public Nullable<int> candidateid { get; set; }
        public Nullable<System.DateTime> applydate { get; set; }
        public string status { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
