//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long taskId { get; set; }
        public string gitUrl { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string taskName { get; set; }
        public Nullable<int> timeTaken { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<System.DateTime> completedDate { get; set; }
    }
}
