//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkillset
    {
        public long id { get; set; }
        public Nullable<long> userId { get; set; }
        public string skills { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
    }
}
