//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManagement
    {
        public long userId { get; set; }
        public string firstName { get; set; }
        public string LastName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<bool> status { get; set; }
        public string roles { get; set; }
        public string grade { get; set; }
        public Nullable<System.DateTime> gradeChangeDate { get; set; }
        public Nullable<long> registeredBy { get; set; }
        public Nullable<long> branchId { get; set; }
        public Nullable<long> reportingTo { get; set; }
    }
}
